apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default
nameSuffix: -dev

images:
- name: jmanzur/hello-app:latest
  newName: 540551285630.dkr.ecr.us-east-1.amazonaws.com/hello-app
  newTag: v3


configMapGenerator:
- literals:
  - TARGET=hermes-ch
  name: hello-app-cm

labels:
- includeSelectors: true
  pairs:
    app: hello-app
    component: hello-app
